deploy_prod:
  stage: deploy
  environment: development
  only:
    - dev
  script:
    # - rsync -av . /home/kijamiid/egt-beta/ --exclude .git --exclude 'lang'
    # - chown -R kijamiid:kijamiid /home/kijamiid/egt-beta/
