<?php

$xpdo_meta_map = array (
  'xPDOObject' => 
  array (
    0 => 'AboutMembers',
    1 => 'AboutPartners',
    2 => 'AboutUs',
    3 => 'Admins',
    4 => 'Alternatives',
    5 => 'Awareness',
    6 => 'Books',
    7 => 'BooksSubmissions',
    8 => 'ContactUsSubmission',
    9 => 'Countries',
    10 => 'Events',
    11 => 'EventsLocations',
    12 => 'EventsSubmissions',
    13 => 'Files',
    14 => 'Home',
    15 => 'Images',
    16 => 'MainImages',
    17 => 'Members',
    18 => 'Members11',
    19 => 'MetaTags',
    20 => 'News',
    21 => 'NewsLetterMails',
    22 => 'OurWork',
    23 => 'Pdfs',
    24 => 'Questions',
    25 => 'Services',
    26 => 'SliderItems',
    27 => 'SliderVideos',
    28 => 'Videos',
    29 => 'YourProject',
  ),
);